services:
  frontend:
    image: salimabouhamidi/winnerfast-frontend:latest
    ports:
      - "5173:5173"  
    networks:
      - app-network

  backend:
    image:  salimabouhamidi/winnerfast-backend:latest
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/winnerfast
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: winnerfast
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge